### PR TITLE
topsStack: add --num-proc for step topo

### PR DESCRIPTION
**Pull request by yunjunz**
This PR includes the following changes:

+ add `stackSentinel.py --num-proc` to pass the number of parallel processes to topo.py, so that mp.Pool() can be independent of OMP_NUM_THREADS, following the discussion at https://github.com/isce-framework/isce2/commit/f06d22e02c43e076e66b19ddcc76506bbefcae2a

+ Stack: check existing orbit with glob instead of os.path.exist(dir)

+ stackSentinel: fix the missing pair between the reference date and the new acquisitions, if the reference date is the most recent "num_conn" acquisition.

Please see the code change for each commit separately, since there is one commit that aligns linebreaks in stackSentinel.createParser().

### CODE REVIEW

**Review by hfattahi — APPROVED** [review]

**Comment by cmarshak** [comment]
Can I use this functionality in topsApp?

**Comment by dbekaert** [comment]
@yunjunz @hfattahi understand this is to overwrite the OMP_NUM_THREADS. Aware of the topsStack/TopsApp differences. Is there a configurable parameter that can be controlled to speed up topo processing for CPU for topsApp or is this only under OMP_NUM_THREADS?

**Comment by yunjunz** [comment]
I don't think the current topsApp has the option to use multiple processes, the only control parameter to speed up is the OMP_NUM_THREADS for multiple threads. 

It should not be difficult to modify the code below to add the multiple processes though:
https://github.com/isce-framework/isce2/blob/def109815df5f724c5dc653878314577e3505c48/components/isceobj/TopsProc/runTopo.py#L25

**Comment by dbekaert** [comment]
@ehavazli Could you take a stab at this under ACCESS? Specifically this would be migrating #99 into TopsApp, specifically the function as identified above by @yunjunz

**Comment by yunjunz** [comment]
@dbekaert I am using topsStack all the time, and do not really have much experience on topsApp. Based on the runtime noted in #99, yes I think it would be useful to have it in topsApp as well.

**Pull request merged**
