### PR TITLE
GPU geo2rdr and topo memory allocation fix

### LINKED ISSUE #331: Bugs in GPU modules
when I build the codes and run topsApp.py on my GPU devices, 
errors "out of memory" and "no kernel image is available for execution on the device" occur in the GPUtopozero module.
A similar problem also exists in the GPUgeo2rdr module.

I modified the file components/zerodop/GPUtopozero/src/Topo.cpp, 
long pixPerImg = (((num_GPU_bytes / 8) / 9) / 1e7) * 1e7; // Round down to the nearest 10M pixels
with
long pixPerImg = 4096*4096; //(((num_GPU_bytes / 8) / 9) / 1e7) * 1e7; // Round down to the nearest 10M pixels ;
and put 
SET_PROPERTY(TARGET GPUgeo2rdr/GPUtopozero PROPERTY CUDA_ARCHITECTURES 50)
into the CMakeLists.txt files.

Then rebuild the codes, the problems disappear.

### PR DESCRIPTION
**Pull request by lijun99**
This PR fixes the memory allocation error for geo2rdr and topo GPU modules, when the GPU has a small memory size (e.g., gaming cards), see Issues #331 and #392. 

N.B.: these GPU modules are designed for GPUs with sufficient double precision support (e.g., K40/P100/V100/A100). However, they still run reasonably faster on gaming cards than CPU modules, even though the speedup is limited.

### CODE REVIEW

**Comment by rtburns-jpl** [comment]
Changes look good, and the CI should be working now so if you rebase you should get green check marks.

**Comment by rtburns-jpl** [comment]
Sorry for the delay, this still looks good so I'll go ahead and merge.

**Comment by CunrenLiang** [comment]
Hi Lijun @lijun99 , this fix leads to out-of-memory problems on my device (NVIDIA RTX A4000). It has 16 G memory.

**Comment by geniusinaction** [comment]
Sorry to dredge up old threads, but I also am having out of memory issues (with a TITAN V card, a Volta-level card which should have great double precision compute, but only 12 GB of onboard RAM). GPU topo does essentially nothing at all:

```
  ------------------ INITIALIZING GPU TOPO ------------------

    Loading slantrange and doppler data...
    Allocating host and general GPU memory...
    Copying general memory to GPU...
    Allocating block memory (163071405 pixels per image)...
    (NOTE: There will be 51 'empty' threads per image block).
    Starting GPU Topo for block 0...
    Sync kernel error: out of memory
    Async kernel error: an illegal memory access was encountered
    GPU finished block 0 in 0.023057 s.
    Copying memory back to host...
    GPU finished block 0 (with memory copies) in 0.263817 s.
    Cleaning device memory and returning to main Topo function...
  Writing block 0 out (asynchronously) to image files...
    Loading slantrange and doppler data...
    Allocating host and general GPU memory...
    Copying general memory to GPU...
    Allocating block memory (163071405 pixels per image)...
    (NOTE: There will be 51 'empty' threads per image block).

```

**Comment by geniusinaction** [comment]
Found Lijun's temporary hack which seems to work! GPU topo now runs without crashing!

https://github.com/lijun99/isce2/commit/af55155cd8778f783508dff9af3ed2442f8f2ea5

**Pull request merged**
