### PR TITLE
Changes on the fetchOrbit.py to download orbit files from the new ESA website

### LINKED ISSUE #267: https://aux.sentinel1.eo.esa.int is down for a couple of days
For a couple of days now, https://aux.sentinel1.eo.esa.int/ site is down so I can't download Sentinel-1 orbit files using fetchOrbit.py. Is it just temporary or has ESA permanently moved the orbit files site to https://scihub.copernicus.eu/gnss/#/home?

### PR DESCRIPTION
**Pull request by bjmarfito**
I've made changes to the fetchOrbit.py to download the files from the https://scihub.copernicus.eu/gnss/#/home. I've used the generic credentials to be able to query and download the Sentinel-1 orbit files.

### CODE REVIEW

**Comment by bjmarfito** [comment]
Forgot to mention that this PR is related to this issue. https://github.com/isce-framework/isce2/issues/267

**Comment by piyushrpt** [comment]
The new API actually allows you to specify validityStart and validityEnd in the query itself. So there should not be a need to create a list for every possible date in the range and then find the right one. They have released reprocessed POEORB that has a processing date that is 5 years from the time period it covers. Using the API might be more prudent to find the file.

**Comment by bjmarfito** [comment]
I've closed and reopened this PR since I've made major changes on the fetchOrbit.py. ESA Copernicus has changed again the download link on the XML of the scihub GNSS Copernicus website. I've integrated the changes on this PR to be able to download again the orbit files from the site.

Here is the result after I've run the edited fetchOrbit.py:

```
(isce2expe) bryanmarfito@Bryans-MacBook-Pro ~ % fetchOrbit_edit.py -i S1B_IW_SLC__1SDV_20210430T095530_20210430T095600_025295_030323_A434.zip
Reference time:  2021-04-30 09:56:00
Satellite name:  S1B
Downloading URL:  https://scihub.copernicus.eu/gnss/odata/v1/Products('ad45b5a6-82b0-43b9-9bd0-4ca36dfef892')/$value
```

Screenshot of the downloaded file:
Screen Shot 2021-05-02 at 8 02 16 PM

Screenshot of the data inside the downloaded orbit file:
Screen Shot 2021-05-02 at 8 03 28 PM

**Review by yjzhenglamarmota — APPROVED** [review]
The script changes the server and modified searching criteria. Looks good to me.
Also tested and works fine.

**Review by yunjunz — APPROVED** [review]
Looks good to me. Testings of both the precise and restituted orbits work without issue. Thank you @bjmarfito!

**Comment by bjmarfito** [comment]
Thank you @yjzhenglamarmota, @yunjunz and @hfattahi for the review and approval on the edits I've made on the code.

**Comment by yuankailiu** [comment]
Hi @bjmarfito, 

Thanks for the update.
At Line 155: <https://github.com/isce-framework/isce2/blob/main/contrib/stack/topsStack/fetchOrbit.py#L155>

In order to make the URL right, I would have to change the index of the string to the following:
`                    match = os.path.join(server[:],resulturl[34:])
`
I am still figuring out why.

**Comment by bjmarfito** [comment]
Thank you @yuankailiu for the heads up. I've checked the url and once again ESA has changed the url in the XML of the downloading site. I've changed line 155 using your suggestion on the fetchOrbit.py and it worked both for precise and restituted orbits. Though based on my testing, I would prefer to use the edits on line 155 below to make it much simpler.

`match = resulturl`

You may submit PR to reflect the changes you've made on the fetchOrbit.py.

**Pull request merged**
