### PR TITLE
Add covariance file output for denseoffsets

### PR DESCRIPTION
**Pull request by juribeparada**
This PR add the covariance output file for denseoffsets (Stripmap and TOPS processing). This simply writes to a file the already calculated covariance values by Ampcor. The generated covariance file includes 3 bands (x, y and xy covariance).

### CODE REVIEW

**Comment by piyushrpt** [comment]
```
        self.snr *= self.scaling_factor
        self.cov1 *= self.scaling_factor
        self.cov2 *= self.scaling_factor
        self.cov3 *= self.scaling_factor
```

I think the scaling of the SNR is a bug and should not be carried over to covariance. We should probably remove the scaling from all of this. This was put in place for using the module with optical data like Landsat/Sentinel-2 where the pixel size is known and scaling pixel offsets to meters needed a simple scale factor.

**Comment by juribeparada** [comment]
I understand, should I remove the scaling only for self.cov* or also for SNR?

**Comment by piyushrpt** [comment]
I think snr as well .. I think this was a bug in the original code.

**Comment by juribeparada** [comment]
OK, scaling_factor removed from cov* and snr

**Review by piyushrpt — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
