### PR TITLE
fix autoRIFT build on centos7 and conda python 3.8

### PR DESCRIPTION
**Pull request by pymonger**
- build autoRIFT using yum-installed opencv (for ARIA docker images)
- fix conda dependency resolution failure
- update SConfigISCE and SConfigISCE.cuda files for python 3.8
- fix CircleCI jobs

### CODE REVIEW

**Comment by rtburns-jpl** [comment]
Interesting, I see this uses opencv from yum. Are there still package conflicts when using conda opencv?

Good to get off netcdf4. @piyushrpt I see one extant import of it in contrib/stack/topsStack/grossOffsets.py - is this possible to remove?

**Comment by piyushrpt** [comment]
That import can be tucked under get_velodata method. I think this is because the velocity fields for Greenland and Antarctica are distributed as netcdf files and used for generating offset guesses

**Comment by pymonger** [comment]
@rtburns-jpl That's right:
```
ops@af1fd1c0792e:~$ conda install opencv
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.                                                                   failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - opencv -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

I removed the explicit conda install of `netcdf4` because the `libnetcdf` installed by that conda package conflicted with the one installed by `gdal`.

**Comment by pymonger** [comment]
Also, if anyone could point me to how we can test autoRIFT, I'll have one of the ARIA SDS developers run those tests and post results here. I've looked at the test scripts at https://github.com/leiyangleon/autoRIFT and https://github.com/leiyangleon/Geogrid but there no direct links to the raw data used in the README examples.

**Comment by rtburns-jpl** [comment]
Pinging @leiyangleon

**Review by piyushrpt — APPROVED** [review]

**Comment by leiyangleon** [comment]
> Also, if anyone could point me to how we can test autoRIFT, I'll have one of the ARIA SDS developers run those tests and post results here. I've looked at the test scripts at https://github.com/leiyangleon/autoRIFT and https://github.com/leiyangleon/Geogrid but there no direct links to the raw data used in the README examples.

@pymonger The radar images we used are
```
S1A_IW_SLC__1SSH_20170221T204710_20170221T204737_015387_0193F6_AB07.zip
S1B_IW_SLC__1SSH_20170227T204628_20170227T204655_004491_007D11_6654.zip
```
and the optical images are
```
LC08_L1TP_020007_20170708_20170716_01_T1_B8.TIF
LC08_L1TP_020007_20170724_20170809_01_T1_B8.TIF
```
The auxiliary input files to Geogrid, e.g. DEM, slope and reference velocity etc, are not publicly available at this moment, because these are being used for production purposes. But one should be able to construct their own input files which are optional, meaning you can also test autoRIFT without these files.

**Pull request merged**
