### PR TITLE
Bake in autoRIFT and add CMake support

### PR DESCRIPTION
**Pull request by rtburns-jpl**
Add autoRIFT to contrib/ for simplified builds + redistribution
Regards https://github.com/conda-forge/isce2-feedstock/pull/19

The README is really nice looking and pleasant to read so I kept it in the subdirectory. To keep the repo size down though, I removed the .png figures and changed the README \ links to point to an external repo.
Preview at https://github.com/rtburns-jpl/isce2/blob/bake-in-autorift/contrib/geo_autoRIFT/README.md

Tested build locally with macOS conda and Nix.

### CODE REVIEW

**Comment by piyushrpt** [comment]
Do we want to pull in geoGrid and autoRIFT physically or as a submodule possibly. We may have to actively migrate any changes made to that repo. What do you prefer?

**Comment by rtburns-jpl** [comment]
Well, if it's a submodule, users will have to use `--recursive` or some lesser-known submodule commands to get the full repo. Also it looks like we have to dump a subdir rather than the toplevel folder, so the autoRIFT repo would have to be restructured.

If you're open to making updates here directly, it can simplify versioning to have everything in one place, and might make your life easier. But if you don't want to, I'm fine with regularly pulling your releases.

**Comment by piyushrpt** [comment]
autoRIFT has a user base that works with optical imagery as well and doesn't need ISCE for it. It has its own conda feedstock as well - to cater to those users. There are a couple of production pipelines that are using isce+autorift at ASF and they rely on the conda packages for it. I think asking those developers to make changes in 2 places might be cumbersome.

**Comment by rtburns-jpl** [comment]
Ok, thanks. I guess monorepo approach and submodule are both off the table then. I'm fine with regularly updating the code to align with autoRIFT releases, since I think that would greatly simplify our builds. But if there are benefits to "baking in" during package construction instead, perhaps I should contribute these CMakeLists upstream?

**Comment by piyushrpt** [comment]
One option is to add CMakeLists to autoRIFT repo and use same approach as scons - if it sees the corresponding sub-folders, add that in parent CMakeLists. 

@leiyangleon - thoughts on pull in frequently from autoRIFT. Are you willing to let us know when you push a change to autoRIFT?

**Comment by leiyangleon** [comment]
> One option is to add CMakeLists to autoRIFT repo and use same approach as scons - if it sees the corresponding sub-folders, add that in parent CMakeLists.
> 
> @leiyangleon - thoughts on pull in frequently from autoRIFT. Are you willing to let us know when you push a change to autoRIFT?

Possibly by the end of August. Alex and I are still working on some new features of it, which has been a while. We will shoot for issuing the next release before Sep.

**Comment by rtburns-jpl** [comment]
@leiyangleon Great! I see that you've been tagging and releasing regularly via github, at https://github.com/leiyangleon/autoRIFT/releases. Assuming you're planning to stick with that approach, I'll subscribe to releases on your repo. Then I'll automatically get a heads up whenever there's a new version for me to bake in.

**Comment by leiyangleon** [comment]
> @leiyangleon Great! I see that you've been tagging and releasing regularly via github, at https://github.com/leiyangleon/autoRIFT/releases. Assuming you're planning to stick with that approach, I'll subscribe to releases on your repo. Then I'll automatically get a heads up whenever there's a new version for me to bake in.

@rtburns-jpl Sure, I will stick with that approach. So feel free to subscribe on my repo.

**Review by piyushrpt — APPROVED** [review]

**Pull request merged**
