### PR TITLE
Replace deprecated numpy types with native types

### LINKED ISSUE #659: New numpy version issues
Hi,

In the latest version of NumPy (1.24), the following attributes have been deprecated, which cause problems running topsApps.py

np.object
np.bool
np.float
np.complex
np.str
np.int

I fixed it by downgrading my numpy to version 1.23.5, but thought I should let you know.

Cheres,
Ekbal

### LINKED ISSUE #660: Erorr after run ./run_05_fullBurst_resample
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
Running: resamp_withCarrier
['--secondary', '/media/ahmed/easythree/Data/secondarys/20210218', '--reference', '/media/ahmed/easythree/Data/reference', '--coregdir', '/media/ahmed/easythree/Data/coreg_secondarys/20210218', '--azimuth_misreg', '/media/ahmed/easythree/Data/misreg/azimuth/dates/20210218.txt', '--range_misreg', '/media/ahmed/easythree/Data/misreg/range/dates/20210218.txt']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Estimated burst offset:  0
Shifts:  {0: 0, 1: 0, 2: -1, 3: 0}
Polynomial Order: 0 - by - 0 
0	
Polynomial Order: 0 - by - 0 
0	
Traceback (most recent call last):
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/resamp_withCarrier.py", line 259, in main
    azCarrPoly, dpoly = secondary.estimateAzimuthCarrierPolynomials(slvBurst, offset = -1.0 * offset)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.10/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 285, in estimateAzimuthCarrierPolynomials
    x = np.arange(0, burst.numberOfSamples,xstep,dtype=np.int)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

### PR DESCRIPTION
**Pull request by rtburns-jpl**
Closes https://github.com/isce-framework/isce2/issues/660

cc @yuankailiu for testing

### CODE REVIEW

**Comment by yuankailiu** [comment]
Thank you. All looks great to me.
My test runs through the steps in `stackSentinel.py`.

**Comment by rtburns-jpl** [comment]
Great to hear, big thanks for testing. I'll go ahead and merge then.

**Comment by InSAR2023** [comment]
I replaced deprecated numpy types with native types. But there is problem in numpy 1.24.
After run_05_fullBurst_resample:

['Function-1']
Running: resamp_withCarrier
['--secondary', '/media/ahmed/easythree/InSAR/EZ-InSAR/secondarys/20200107', '--reference', '/media/ahmed/easythree/InSAR/EZ-InSAR/reference', '--coregdir', '/media/ahmed/easythree/InSAR/EZ-InSAR/coreg_secondarys/20200107', '--azimuth_misreg', '/media/ahmed/easythree/InSAR/EZ-InSAR/misreg/azimuth/dates/20200107.txt', '--range_misreg', '/media/ahmed/easythree/InSAR/EZ-InSAR/misreg/range/dates/20200107.txt']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Estimated burst offset:  0
Shifts:  {0: 0, 1: 0, 2: 0, 3: -1}
Polynomial Order: 0 - by - 0 
0	
Polynomial Order: 0 - by - 0 
0	
Traceback (most recent call last):
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/resamp_withCarrier.py", line 259, in main
    azCarrPoly, dpoly = secondary.estimateAzimuthCarrierPolynomials(slvBurst, offset = -1.0 * offset)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.9/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 285, in estimateAzimuthCarrierPolynomials
    x = np.arange(0, burst.numberOfSamples,xstep,dtype=np.int)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
Completed Parsing the Configuration file
Functions to be executed:

**Comment by yuankailiu** [comment]
I can see from your error message that line 285 in `TOPSSwathSLCProduct.py` is still using `np.int`.
How did you update your code? You can manually change this line. 
Since now this updated code is merged to the main branch, you can `git pull` the whole branch and recompile ISCE2 to replace your current code.

**Comment by InSAR2023** [comment]
> I can see from your error message that line 285 in `TOPSSwathSLCProduct.py` is still using `np.int`. How did you update your code? You can manually change this line. Since now this updated code is merged to the main branch, you can `git pull` the whole branch and recompile ISCE2 to replace your current code.

I had modified the codes in this path ("/home/ahmed/tools_insar/proc_insar/isce2/), but they were not modified in the path below:
"/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/isce
By modifying the codes, version 1.24 works now.
Thanks a lot.

**Pull request merged**
