### PR TITLE
Bump autoRIFT 1.0.6 -> 1.0.7

### PR DESCRIPTION
**Pull request by rtburns-jpl**
Update to @leiyangleon's latest upstream release.
https://github.com/leiyangleon/autoRIFT/compare/v1.0.6...v1.0.7

### CODE REVIEW

**Review by piyushrpt — APPROVED** [review]

**Comment by leiyangleon** [comment]
@rtburns-jpl do you know when this will be available in Conda forge of ISCE?

**Comment by rtburns-jpl** [comment]
Shortly after we make our next github release. Happy to go ahead and make a v2.4.1 hotfix release if this is holding you up, looks like we've already merged a couple bugfixes which will be quite welcome to our users.
https://github.com/isce-framework/isce2/compare/v2.4.0...ba2cb412eabcd7a54c2b35c00967b4678d4d33ef

**Comment by leiyangleon** [comment]
That would be great if the next release can happen soon.

**Comment by leiyangleon** [comment]
BTW, scikit-image was used by autoRIFT but not by ISCE. You might want to add that to the conda recipe's dependencies.

**Comment by leiyangleon** [comment]
@rtburns-jpl I posted a runtime comparison [question](http://earthdef.caltech.edu/boards/4/topics/3614) across different ISCE versions on the ISCE forum. So far, I haven't heard anything from the forum maintainers and thus wonder if you would know or could direct this question to somebody who might know it.

**Comment by rtburns-jpl** [comment]
Sure - there's nothing I'm immediately aware of that would have caused that issue, but I've passed along your question to the other isce developers

**Pull request merged**
