### PR TITLE
stripmapStack/topo: call gdal2isce_xml.py inside runMultilook() if xml file missing

### PR DESCRIPTION
**Pull request by yunjunz**
This PR fixes the bug of sometimes missing xml files during runMultilook() with gdal. Detailed changes are as below:

+ topo: merge runMultilookGdal() into runMultilook() with new argument "method" to control to use isce Looks module (averaging) or gdal_translate (extraction; default, same as before).

+ topo: call gdal2isce_xml.py so that xml file for multilooked data are always generate. This fix the warning message from gdal_translate: "Warning 1: Geotransform matrix has non rotational terms"

+ topo: skip multilooking if the data file has vrt/xml file missing, which sometimes happens to incLocal and shadowMask (don't know the cause yet; I used GPU version).

+ crossmul/resampleSlc: re-organize module import at the top of scripts

### CODE REVIEW

**Comment by piyushrpt** [comment]
Would it be possible to eliminate the system calls with python calls for gdal_translate with gdal.Translate and gdal2isce_xml with the updates you made?

**Comment by yunjunz** [comment]
Hi @piyushrpt, the new commit is now using `gdal.Translate()`. 

I did not use the pythonic `gdal2isce_xml()` because this function is imported from `applications`.  Considering the `conda install isce2` users (including myself), this function won't be available until the next condo build. Maybe we should wait until then to replace it? If there is another way to import it now, please let me know.

**Comment by piyushrpt** [comment]
I think something like this would always work, even with conda as it essentially follows the python package directory structure.

```
from isce.applications.gdal2isce_xml import gdal2isce_xml 
```

**Comment by piyushrpt** [comment]
I see what you are saying about the python interface not being available in conda from the release. Lets open a ticket for this in issues and close it on next release.

**Review by piyushrpt — APPROVED** [review]

**Review by hfattahi — APPROVED** [review]

**Pull request merged**
