### PR TITLE
More https changes in isceobj iscesys alos2proc

### PR DESCRIPTION
**Pull request by EJFielding**
Changed other files with hard-coded SRTM or SWBD URL to https

### CODE REVIEW

**Comment by EJFielding** [comment]
@rtburns-jpl I see that my `Atom` editor made similar whitespace changes in several of the files that I edited, but I hope these are not so distracting as in the `release_history.py` file at the top level of the repository.

**Comment by rtburns-jpl** [comment]
Yeah, I suppose that's fine here. I would recommend disabling that feature for future PRs though.

**Comment by EJFielding** [comment]
Thanks, Ryan!

Does this also get included into the conda-forge version of isce2?

++Eric


From: Ryan Burns ***@***.***>
Reply-To: isce-framework/isce2 ***@***.***>
Date: Thursday, August 11, 2022 at 8:57 AM
To: isce-framework/isce2 ***@***.***>
Cc: "Fielding, Eric J (US 329A)" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [isce-framework/isce2] More https changes in isceobj iscesys alos2proc (PR #562)


Merged #562<https://urldefense.us/v3/__https:/github.com/isce-framework/isce2/pull/562__;!!PvBDto6Hs4WbVuu7!fVU_7np-k_YlXP0heCRqFelqrJ3sPs96q6SoAlX_3PDWpu-xg1XPOKVgAgV1GOpMZFXZhfGh0w$> into main.

**Comment by rtburns-jpl** [comment]
Not automatically, we have to manually cut a new release and update the conda-forge recipe for the conda package to be updated as well. So if you need to use these bugfixes before the next bugfix release, you’ll need to build from source.

From: Eric Fielding ***@***.***>
Reply-To: isce-framework/isce2 ***@***.***>
Date: Thursday, August 11, 2022 at 9:51 AM
To: isce-framework/isce2 ***@***.***>
Cc: "Burns, Ryan T (US 334K)" ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL] Re: [isce-framework/isce2] More https changes in isceobj iscesys alos2proc (PR #562)

Thanks, Ryan!

Does this also get included into the conda-forge version of isce2?

++Eric


From: Ryan Burns ***@***.***>
Reply-To: isce-framework/isce2 ***@***.***>
Date: Thursday, August 11, 2022 at 8:57 AM
To: isce-framework/isce2 ***@***.***>
Cc: "Fielding, Eric J (US 329A)" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [isce-framework/isce2] More https changes in isceobj iscesys alos2proc (PR #562)


Merged #562<https://urldefense.us/v3/__https:/github.com/isce-framework/isce2/pull/562__;!!PvBDto6Hs4WbVuu7!fVU_7np-k_YlXP0heCRqFelqrJ3sPs96q6SoAlX_3PDWpu-xg1XPOKVgAgV1GOpMZFXZhfGh0w$> into main.

**Pull request merged**
