### PR TITLE
StAMPS preprocessor and stackprocessors minor modification

### PR DESCRIPTION
**Pull request by bjmarfito**
- Removed excess backslash in make_single_reference_stack_isce which inhibited the generation of files needed for StAMPS
- Removed unused imp library in topsStack and stripmapStack
- Fixed spacing on the datetime library in topsStack and stripmapStack

### CODE REVIEW

**Review by rtburns-jpl — APPROVED** [review]
LGTM, thanks!

**Review by hfattahi — APPROVED** [review]
LGTM

**Comment by bjmarfito** [comment]
Thank you @rtburns-jpl and @hfattahi!

**Comment by PeymanPython** [comment]
@hfattahi 
Many thanks for your all kind help.
Could you please introduce me the best way/tutorial to link the ISCE2StaMPS? I'v already produced the ifgs through ISCE.
Thanks in advance

**Comment by bjmarfito** [comment]
@PeymanPython as far as I know, you need to use a stack of SLCs not a stack of interferograms to generate files needed for StAMPS. You must use the argument `-W slc` to generate a stack of SLCs. 

A manual was already created for ISCE2StaMPS. Here is the link: https://github.com/isce-framework/isce2-docs/blob/master/StackToStaMPS_Manual/Manual.pdf. You must take note that the terms master and slave were already discarded since ISCEv2.4 and instead it now uses the terms reference and secondary.

**Pull request merged**
