### PR TITLE
upgraded syntax of ALOS_pre_process/readOrbitPulse.f and ISSI/src/igrf2005_sub.f to compile with new gfortran

### PR DESCRIPTION
**Pull request by EJFielding**

### CODE REVIEW

**Review by rtburns-jpl — APPROVED** [review]
LGTM, thanks!

**Review by hfattahi — APPROVED** [review]
LGTM!

**Comment by rtburns-jpl** [comment]
I like your original changes but I'd like to avoid adding `-fallow-argument-mismatch` - I think it would be preferable to resolve any argument mismatches in the code itself if possible. I opened https://github.com/isce-framework/isce2/pull/441 to hopefully do so, would appreciate a look if you have time.

**Comment by EJFielding** [comment]
@rtburns-jpl Should I remove the change to [sconsConfigFile.py] from this PR? (https://github.com/isce-framework/isce2/pull/435/commits/a8443b3b7726fd64f90b3bc2d285a08ad3569d0e)

**Comment by rtburns-jpl** [comment]
Yes, thanks - then I think we are good to merge

**Comment by rtburns-jpl** [comment]
Thanks!

**Pull request merged**
