### PR TITLE
improvements for ALOS-2 ionospheric correction and interferogram filtering

### PR DESCRIPTION
**Pull request by CunrenLiang**
1. use FFTW for psfiltering
2. enhanced merging of subswaths for ALOS-2 ionospheric correction over poor coherence areas

These only affect ALOS-2 processing, so no need for additional review.

### CODE REVIEW

**Review by hfattahi — APPROVED** [review]

**Comment by piyushrpt** [comment]
Any specific reason to create ps_filt1.c instead of updating and improving ps_filt.c ?

**Comment by CunrenLiang** [comment]
New psfilter can use different window size.

**Comment by piyushrpt** [comment]
Again, why cant this be accommodated as an update to an existing module. Do we need have a whole new copy of the code in a different module?

**Comment by CunrenLiang** [comment]
the code is not modified from the ISCE verison. I can remove the one in mroipac/filter, and place this one in mroipac/filter, but I think this requires some changes in other scripts also.

**Comment by CunrenLiang** [comment]
Just took another look of the filter in mroipac/filter, I found it has changed a lot from the roi_pac version including defines and header files. It would take a lot of time to merge the version in alos2filter and mroipac/filter.

**Comment by piyushrpt** [comment]
I'm a little hesitant to have multiple versions of everything - definite recipe for disaster and for things going out of sync. This is not ideal. For future developments, could you see if the functionality already exists in isce and start from that?

**Review by piyushrpt — APPROVED** [review]

**Pull request merged**
