### PR TITLE
Changed SRTM download to `https`

### PR DESCRIPTION
**Pull request by EJFielding**
LP DAAC now requires `https` and refuses the `http` connections.

### CODE REVIEW

**Comment by EJFielding** [comment]
I could not figure out how to get rid of all those earlier commits in my fork as they were merged into ISCE2 already. I ran `rebase` locally.

**Comment by rtburns-jpl** [comment]
You should fetch our upstream, isce-framework/isce2, and rebase onto that rather than your fork, dropping any commits which have already been merged. Happy to do that for you if it would be easier.

**Comment by EJFielding** [comment]
@rtburns-jpl I did fetch the upstream and rebase to that, but then when I pushed it to my fork, it did not remove the merged commits. Feel free to delete them!

**Comment by rtburns-jpl** [comment]
Never mind, it looks like I can't push to this branch because it's issued from your main branch, which is protected. Please either remove the branch protections from your main branch or reissue this PR from a different branch. In the future, I'd recommend issuing PRs from separate branches, as it's easier to keep the git history of your fork sane that way.

**Comment by EJFielding** [comment]
If you want to go ahead make those few tiny URL changes in a new branch, go ahead. I am sorry I did not make a new branch when I started the small edits.

**Comment by rtburns-jpl** [comment]
No worries, I'll open a new PR with the rebased commits.

**Pull request closed without merging**
