### PR TITLE
Remove use of deprecated XML ElementTree getchildren method

### LINKED ISSUE #265: ElementTree.Element.getchildren() removed in python 3.9
I insatlled the latest version of ISCE (v2.5.1), and when I use the stack model to prepare interferograms for the times-series process(using Mintpy). I met this problem. I listed the files and dictionaries (DEM AuxDir Orbits SLC) and error message.

 (isce2) guangbao@guangbao-BAD-INDEX:~/ISCE$ ^C
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE$ cd AuxDir/
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/AuxDir$ ls
data  manifest.safe  support
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/AuxDir$ cd SLC
bash: cd: SLC: No such file or directory
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/AuxDir$ cd ..
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE$ cd SLC
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/SLC$ ls
S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip
S1B_IW_SLC__1SDV_20180521T221211_20180521T221238_011025_014336_38A0.zip
S1B_IW_SLC__1SDV_20180602T221212_20180602T221239_011200_0148E0_4F05.zip
S1B_IW_SLC__1SDV_20180614T221213_20180614T221240_011375_014E44_06CB.zip
S1B_IW_SLC__1SDV_20180626T221213_20180626T221240_011550_0153AF_5390.zip
S1B_IW_SLC__1SDV_20180708T221214_20180708T221241_011725_01591E_0B8A.zip
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/SLC$ cd ..
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE$ cd DEM/
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/DEM$ ls
demLat_N38_N40_Lon_E116_E118.dem.wgs84      demLat_N38_N40_Lon_E116_E118.dem.wgs84.xml  isce.log
demLat_N38_N40_Lon_E116_E118.dem.wgs84.vrt  insar.log
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/DEM$ cd ..
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE$ cd Orbits/
(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE/Orbits$ ls
S1B_OPER_AUX_POEORB_OPOD_20180529T110601_V20180508T225942_20180510T005942.EOF
S1B_OPER_AUX_POEORB_OPOD_20180610T110539_V20180520T225942_20180522T005942.EOF
S1B_OPER_AUX_POEORB_OPOD_20180622T110648_V20180601T225942_20180603T005942.EOF
S1B_OPER_AUX_POEORB_OPOD_20180704T110539_V20180613T225942_20180615T005942.EOF
S1B_OPER_AUX_POEORB_OPOD_20180716T110549_V20180625T225942_20180627T005942.EOF
S1B_OPER_AUX_POEORB_OPOD_20180728T110605_V20180707T225942_20180709T005942.EOF

(isce2) guangbao@guangbao-BAD-INDEX:~/ISCE$ SentinelWrapper.py -c configs/config_reference 
/home/guangbao/anaconda3/envs/isce2/isce2/contrib/stack/topsStack/SentinelWrapper.py:113: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if iString is '':
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip', '--swaths', '1 2 3', '--orbitdir', '/home/guangbao/ISCE/Orbits', '--outdir', '/home/guangbao/ISCE/reference', '--auxdir', '/home/guangbao/ISCE/AuxDir', '--bbox', '38 39 116 117', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Input XML files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/annotation/s1b-iw1-slc-vv-20180509t221211-20180509t221236-010850-013d8b-004.xml']
Input TIFF files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/measurement/s1b-iw1-slc-vv-20180509t221211-20180509t221236-010850-013d8b-004.tiff']
Manifest files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/manifest.safe']
MANS:  /home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/manifest.safe
Setting IPF version to :  002.90
'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
Input XML files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/annotation/s1b-iw2-slc-vv-20180509t221212-20180509t221237-010850-013d8b-005.xml']
Input TIFF files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/measurement/s1b-iw2-slc-vv-20180509t221212-20180509t221237-010850-013d8b-005.tiff']
Manifest files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/manifest.safe']
MANS:  /home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/manifest.safe
Setting IPF version to :  002.90
'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
Input XML files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/annotation/s1b-iw3-slc-vv-20180509t221210-20180509t221236-010850-013d8b-006.xml']
Input TIFF files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/measurement/s1b-iw3-slc-vv-20180509t221210-20180509t221236-010850-013d8b-006.tiff']
Manifest files:  ['/vsizip//home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/manifest.safe']
MANS:  /home/guangbao/ISCE/SLC/S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.zip S1B_IW_SLC__1SDV_20180509T221210_20180509T221237_010850_013D8B_B303.SAFE/manifest.safe
Setting IPF version to :  002.90
'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
Running: topo
['--reference', '/home/guangbao/ISCE/reference', '--dem', '/home/guangbao/ISCE/DEM/demLat_N38_N40_Lon_E116_E118.dem.wgs84', '--geom_referenceDir', '/home/guangbao/ISCE/geom_reference', '--numProcess', '1']
running in parallel with 1 processes
Traceback (most recent call last):
  File "/home/guangbao/anaconda3/envs/isce2/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/guangbao/anaconda3/envs/isce2/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/guangbao/anaconda3/envs/isce2/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/guangbao/anaconda3/envs/isce2/isce2/contrib/stack/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

It seems that this is the cause of python version(I am using v3.9.2), and I am trying to fix this problem, I will post the result if I fixed this problem. And I hope all of your kind help if you have any solution. Thank you very much.

### PR DESCRIPTION
**Pull request by rtburns-jpl**
Fixes #265

cc @scottyhq

### CODE REVIEW

**Comment by scottyhq** [comment]
Thanks @rtburns-jpl! *Looks* fine to me, but I'm not sure of your preferred approach for testing changes like this? I can see the .circle CI builds ISCE (just against python version 3.8 I think), and runs some basic import tests. But I don't see anything for *running* apps against valid XML example files. 
https://github.com/isce-framework/isce2/blob/19b754dd1adb9bc767eb6523c71eb33acaee073f/.circleci/config.yml#L53-L55

So I'm inferring the manual testing strategy is 1. checkout PR code, 2. build isce from source. 3. run some choice workflows.

It'd be nice to capture in a test the outcome of `topsApp.py --dostep=startup` (similarly for the other sensors). Because #265 is just failing in the XML parsing. It seems like the circleci is config is specific for publishing hysds docker containers, not sure I should mess with that. So if it's of interest I could add a PR with a GitHub Action with a matrix test against different python versions for topsApp? @piyushrpt , thoughts?

**Comment by rtburns-jpl** [comment]
Yeah, I was hoping one of our TOPS users would be willing to build and test manually, as unfortunately that's the only way to get an in-depth test currently. Running the startup step on a sample XML seems like a great idea to me. It's hard to exercise any end-to-end functionality as this would require large datasets, but parsing some example XMLs seems like another good check we should be doing.

**Comment by scottyhq** [comment]
Here is a solution to test topsApp.py through 'preprocess' various python versions using github actions that I could contribute in another PR: https://github.com/scottyhq/isce2/blob/main/.github/workflows/topsApp.yml . I think it could easily be extended to do more tests or separate workflows could be done in the same way for other apps. 

I tested this in my fork, you can see the logs here https://github.com/scottyhq/isce2/pull/2/checks?check_run_id=2583712432

**Comment by rtburns-jpl** [comment]
Nice! That looks great, and should be pretty straightforward to adapt for our circleci setup. I tried the topsApp command locally and it reproduces the error.

**Comment by rtburns-jpl** [comment]
OK, if no one objects, I'll merge this shortly and make a new bugfix release so we can get the python39 conda package working again.

**Pull request merged**
