### PR TITLE
use circleci workflows for test, docker build, and deploy to dockerhub

### PR DESCRIPTION
**Pull request by pymonger**
We may need to iterate configuring the proper settings in the circleci dashboard.

- renamed "build" job to "test" and created "test" workflow
  - will run on all pull requests and merges into master
- "build" job now builds isce docker container
- "deploy" job will deploy docker image to dockerhub at isce/isce2 (https://cloud.docker.com/u/isce/repository/list)
  - need to configure DOCKER_PASS and DOCKER_USER in "Build Settings" -> "Envrionment Variables" on circleci
- created "build-deploy" workflow to run "build" job then "deploy" job on merge of PR to master
- created "build-periodically" workflow to run "build-periodically" job then "deploy" job once a week

### CODE REVIEW

**Comment by piyushrpt** [comment]
@pymonger ... We would need some help from you to debug this issue. Do you want me to change any settings on the CI System for this?

**Comment by piyushrpt** [comment]
I have updated the CI system with credentials. Would you want to test it before merging this?

**Comment by pymonger** [comment]
@piyushrpt: yes, let me test. But now I'm thinking the container should mirror the installation of isce as it is installed if you do `conda install`. We currently install isce to /opt but conda installs it in its normal site-packages.

**Comment by pymonger** [comment]
@piyushrpt: The `build-deploy` workflow worked fine from my forked branch and was able to push it up to dockerhub: https://cloud.docker.com/u/isce/repository/docker/isce/isce2. We should be good to go. When you merge this PR, it should retrigger the `test` and `build-deploy` workflows to run under the circleci account you configured and we should be able to see if the push to dockerhub works from there. I guess we can defer sorting out the installation location of isce in the container for a different github issue. The main point of this PR is to establish an end-to-end test, build, and deploy workflow.

**Comment by piyushrpt** [comment]
Awesome ... thank you for these updates.

**Pull request merged**
