### PR TITLE
ionospheric phase estimation module for topsStack

### PR DESCRIPTION
**Pull request by CunrenLiang**
This is the ionospheric phase estimation module for the topsStack processor in
contrib/stack/topsStack

1. The new ionospheric phase estimation module is added as another stack module in stackSentinel.py as other four stack modules including slc, correlation, interferogram, and offset.

2. By default ionospheric phase estimation is turned off. When the ionospheric phase estimation is turned on in any of the four stack workflows including slc, correlation, interferogram, and offset, the corresponding configure files and run files are generated as well. These run files can be executed after executing the regular stack run files. There are no interactions between regular stack module and ionospheric phase estimation module in regular stack processing, so regular stack processing is not affected.

3. The result is ionospheric phase of each date in a folder named ion_dates.

4. README.md is updated as well for usage of the new ionospheric phase estimation module.

### CODE REVIEW

**Comment by hfattahi** [comment]
@yuankailiu Can I assume that you have extensively tested this PR?

**Comment by hfattahi** [comment]
> > @yuankailiu Can I assume that you have extensively tested this PR?
> 
> I have tested the PR for topsStack processor in `contrib/stack/topsStack`. The ionosphere phase estimation there can be implemented without issues. The ionospheric phases are consistent with those processed from `topsApp.py`. This was tested in two tracks, each of about 300 interferograms.
> 
> I have not tested any ALOS codes though.

Thank you @yuankailiu . Your input is very helpful.

**Comment by yuankailiu** [comment]
FYI, here are some figures of one particular pair. Also maybe you can identify potential issues that I never notice!

Left to right panels are:
(1). unwrapped phase of regular interferogram without ionosphere correction
(2). estimated ionospheric phase
(3). unwrapped phase with ionosphere correction (1 minus 2)

Little difference between topsStack and topsApp:
1. `topsApp` has subtracted the iono phases before unwrapping the regular interferograms. Thus to get the uncorrected unwrapped phase for my interferograms, I had to add the iono phases back to the corrected unwrapped phase. Whereas `topsStack` unwraps and saves the iono phases and regular unwrapped phases separately. Thus the correction is done after unwrapping.
2. `topsStack` currently has no option to compute the jumps on the burst edges. `topsApp` can do that.


ps. ignore the reference pixel shown there. No reference pixel is applied.

### [Shown as wrapped colormap]
**topsStack:**
image

**topsApp:**
image

### [Shown as regular colormap]
**topsStack:**
image

**topsApp:**
image

**Comment by hfattahi** [comment]
> FYI, here are some figures of one particular pair. Also maybe you can identify potential issues that I never notice!
> 
> Left to right panels are: (1). unwrapped phase of regular interferogram without ionosphere correction (2). estimated ionospheric phase (3). unwrapped phase with ionosphere correction (1 minus 2)
> 
> Little difference between `topsStack` and `topsApp` ionospheric phase estimation modules:
> 
> 1. `topsApp` has subtracted the iono phases before unwrapping the regular interferograms. Thus to get the uncorrected unwrapped phase for my interferograms, I had to add the iono phases back to the corrected unwrapped phase. Whereas `topsStack` unwraps and saves the iono phases and regular unwrapped phases separately. Thus the correction is done after unwrapping.
> 2. `topsStack` currently has no option to compute the jumps on the burst edges. `topsApp` can do that.
> 
> ps. ignore the reference pixel shown there. No reference pixel is applied.
> 
> ### [Shown as wrapped colormap]
> **topsStack:** image
> 
> **topsApp:** image
> 
> ### [Shown as regular colormap]
> **topsStack:** image
> 
> **topsApp:** image
> 
> figures made using some functions in MintPy.

Very interesting results @yuankailiu . Thanks for sharing. Have you by any chance quantified the difference between the estimated ionospheric phases from topsApp and topsStack? From the figure, there seems to be a long-wavelength difference but it could be just the slightly different colorscale and different reference points. Would be really good to subtract the two estimated ionospheric phases and look at the difference with small colorscale or even a profile along the azimuth direction. Thanks for clarifying the different functionalities for burst jumps.

**Comment by CunrenLiang** [comment]
> > FYI, here are some figures of one particular pair. Also maybe you can identify potential issues that I never notice!
> > Left to right panels are: (1). unwrapped phase of regular interferogram without ionosphere correction (2). estimated ionospheric phase (3). unwrapped phase with ionosphere correction (1 minus 2)
> > Little difference between `topsStack` and `topsApp` ionospheric phase estimation modules:
> > 
> > 1. `topsApp` has subtracted the iono phases before unwrapping the regular interferograms. Thus to get the uncorrected unwrapped phase for my interferograms, I had to add the iono phases back to the corrected unwrapped phase. Whereas `topsStack` unwraps and saves the iono phases and regular unwrapped phases separately. Thus the correction is done after unwrapping.
> > 2. `topsStack` currently has no option to compute the jumps on the burst edges. `topsApp` can do that.
> > 
> > ps. ignore the reference pixel shown there. No reference pixel is applied.
> > ### [Shown as wrapped colormap]
> > **topsStack:** image
> > **topsApp:** image
> > ### [Shown as regular colormap]
> > **topsStack:** image
> > **topsApp:** image
> > figures made using some functions in MintPy.
> 
> Very interesting results @yuankailiu . Thanks for sharing. Have you by any chance quantified the difference between the estimated ionospheric phases from topsApp and topsStack? From the figure, there seems to be a long-wavelength difference but it could be just the slightly different colorscale and different reference points. Would be really good to subtract the two estimated ionospheric phases and look at the difference with small colorscale or even a profile along the azimuth direction. Thanks for clarifying the different functionalities for burst jumps.

Thanks for checking this PR. I have compared the ionospheric phase estimation results from topsApp and topsStack during the development. They are the same. Like Kai said, burst discontinuities are not considered in topsStack. This feature is included in topsApp as an option.

**Comment by hfattahi** [comment]
> > > FYI, here are some figures of one particular pair. Also maybe you can identify potential issues that I never notice!
> > > Left to right panels are: (1). unwrapped phase of regular interferogram without ionosphere correction (2). estimated ionospheric phase (3). unwrapped phase with ionosphere correction (1 minus 2)
> > > Little difference between `topsStack` and `topsApp` ionospheric phase estimation modules:
> > > 
> > > 1. `topsApp` has subtracted the iono phases before unwrapping the regular interferograms. Thus to get the uncorrected unwrapped phase for my interferograms, I had to add the iono phases back to the corrected unwrapped phase. Whereas `topsStack` unwraps and saves the iono phases and regular unwrapped phases separately. Thus the correction is done after unwrapping.
> > > 2. `topsStack` currently has no option to compute the jumps on the burst edges. `topsApp` can do that.
> > > 
> > > ps. ignore the reference pixel shown there. No reference pixel is applied.
> > > ### [Shown as wrapped colormap]
> > > **topsStack:** image
> > > **topsApp:** image
> > > ### [Shown as regular colormap]
> > > **topsStack:** image
> > > **topsApp:** image
> > > figures made using some functions in MintPy.
> > 
> > 
> > Very interesting results @yuankailiu . Thanks for sharing. Have you by any chance quantified the difference between the estimated ionospheric phases from topsApp and topsStack? From the figure, there seems to be a long-wavelength difference but it could be just the slightly different colorscale and different reference points. Would be really good to subtract the two estimated ionospheric phases and look at the difference with small colorscale or even a profile along the azimuth direction. Thanks for clarifying the different functionalities for burst jumps.
> 
> Thanks for checking this PR. I have compared the ionospheric phase estimation results from topsApp and topsStack during the development. They are the same. Like Kai said, burst discontinuities are not considered in topsStack. This feature is included in topsApp as an option.

Thank you @CunrenLiang. I'm sorry for delay in reviewing this PR. We will get to it very soon.

**Review by hfattahi — APPROVED** [review]
Thank you @CunrenLiang for this very useful PR which adds ionospheric phase estimation to the stack processor. Sorry for the delay in reviewing. This addition looks good to me.

**Comment by CunrenLiang** [comment]
> Thank you @CunrenLiang for this very useful PR which adds ionospheric phase estimation to the stack processor. Sorry for the delay in reviewing. This addition looks good to me.

Thank you for processing this PR @hfattahi !

**Review by yunjunz — APPROVED** [review]
Looks good to me too. Thank you @CunrenLiang for this long-desired PR!

**Comment by yuankailiu** [comment]
@hfattahi, below is the figure to quantify the difference between the estimated ionospheric phases from topsApp and topsStack.  The comparison is done for only one pair here.

Left is from `topsApp` (note the burst-boundary effects)
Middle is from `topsStack`
Right is `topsStack` minus `topsApp`

They are all referenced to the same pixel. The unit is radian. The left and middle have the same color range. The right has a tiny color range.
iono_compare_modules

The difference after subtracting the two estimated ionospheric phases look only has some variation due to the burst-boundary effects. 

This is the profile along the azimuth direction:
iono_compare_modules_prof

**Comment by hfattahi** [comment]
> @hfattahi, below is the figure to quantify the difference between the estimated ionospheric phases from topsApp and topsStack. The comparison is done for only one pair here.
> 
> Left is from `topsApp` (note the burst-boundary effects) Middle is from `topsStack` Right is `topsStack` minus `topsApp`
> 
> They are all referenced to the same pixel. The unit is radian. The left and middle have the same color range. The right has a tiny color range. iono_compare_modules
> 
> The difference after subtracting the two estimated ionospheric phases look only has some variation due to the burst-boundary effects. Sorry that I don't have the iono phases from topsApp without taking into account the burst-boundary jumps.
> 
> This is the profile along the azimuth direction (unit is also radian): iono_compare_modules_prof

Thanks @yuankailiu for the update. I appreciate that. 
Could you clarify about the profile plot. Does the plot represents multiple profiles parallel to the dotted line ? 
I would have expected an almost saw-tooth plot with zero mean. I assume your profile is sampled and that's why we don't see the saw-tooth pattern (which is fine). But I'm concerned why the plot shows a long-wavelength pattern up to 0.4 radian (which is not too small to ignore).  Not clear to me why the end of those profiles vary from -0.8 to 0.4 radian?

**Comment by hfattahi** [comment]
> @hfattahi,
> 
> The saw-tooth shape is still there, better shown with line connected dots.
> 
> So yes, there seems to be a long-wavelength trend that the variation of the difference of the ionosphere phases within each burst gets larger toward south.
> 
> The resolution is only ~900m, but from the map, we can see this trend as well.
> 
> bf566e34-c9de-4241-b387-2a5cc20984b6
> 
> image

thank you @yuankailiu for the clarification. The profile now makes sense to me. I think the difference between the two is well documented here.

@CunrenLiang would you please elaborate what was the reason to not include the jumps in the iono estimation for the stack? Also, How do you want to move forward from here with this PR? I suggest that we go ahead and merge it and open an issue, documenting the difference between the iono estimates from topsApp and topsStack.

**Comment by yuankailiu** [comment]
@hfattahi, @CunrenLiang, to follow up on that. We can also see this variation before doing the difference between topsApp & topsStack

For this particular pair of ionosphere, there's a slope change in the middle of the track. This is clear in topsStack (no burst jumps considered).

In the topsApp result, in addition to long-wavelength slope change, the slope of each burst also become larger. Is this expected? Sorry I don't understand the theory well. 

image

**Comment by CunrenLiang** [comment]
> > @hfattahi,
> > The saw-tooth shape is still there, better shown with line connected dots.
> > So yes, there seems to be a long-wavelength trend that the variation of the difference of the ionosphere phases within each burst gets larger toward south.
> > The resolution is only ~900m, but from the map, we can see this trend as well.
> > bf566e34-c9de-4241-b387-2a5cc20984b6
> > image
> 
> thank you @yuankailiu for the clarification. The profile now makes sense to me. I think the difference between the two is well documented here.
> 
> @CunrenLiang would you please elaborate what was the reason to not include the jumps in the iono estimation for the stack? Also, How do you want to move forward from here with this PR? I suggest that we go ahead and merge it and open an issue, documenting the difference between the iono estimates from topsApp and topsStack.

That could be included, but I did not have that much time for it. In the discussion with Mark, we have mostly focused on efficiency and ignored the burst discontinuities. It can be included in the future though.

Final ionosphere from tops stack processing is based on ls estimation of individual pairs. The long-wavelength difference should be caused by the limited precision in the original ionosphere estimation before filtering. This error should be random in time or for individual pairs. I would go ahead and merge the PR.

**Comment by CunrenLiang** [comment]
> @hfattahi, @CunrenLiang, to follow up on that. We can also see this variation before doing the difference between topsApp & topsStack
> 
> For this particular pair of ionosphere, there's a slope change in the middle of the track. This is clear in topsStack (no burst jumps considered).
> 
> In the topsApp result, in addition to long-wavelength slope change, the slope of each burst also become larger. Is this expected? The burst jump variation is larger when the absolute iono phase is larger. Sorry I don't understand the theory well.
> 
> image

It's normal. It depends on the azimuth changing rate of the original ionospheric phase.

**Comment by hfattahi** [comment]
@CunrenLiang thank you for the clarification. I agree that we can move forward with this PR.
@yuankailiu I agree with Cunren that your observation is expected.

**Comment by rtburns-jpl** [comment]
Awesome to have this new module, you guys think it's time for a v2.6 release?

**Comment by hfattahi** [comment]
@rtburns-jpl yes I think this is important enough to make a release.

**Pull request merged**
