### PR TITLE
Changed SRTM download to `https`

### PR DESCRIPTION
**Pull request by rtburns-jpl**
cc @EJFielding (https://github.com/isce-framework/isce2/pull/558)

### CODE REVIEW

**Comment by EJFielding** [comment]
Thanks for the clean PR! Can you go ahead and merge this? I tested a `dem.py` download and it now works.

**Comment by EJFielding** [comment]
For some reason, I can download the URLs with `wget` from a command line, but the `curl` command that is run from inside `dem.py` is connecting but not getting any data. They should be using the same `$HOME/.netrc` file.

**Comment by EJFielding** [comment]
The `dem.py` run did finally finish after about 15 minutes, so the URL is correct but the servers still have some capacity issues.

**Comment by kylemurray2** [comment]
I had to add the 'https' to iscesys/DataManager/SWBDManager.py get the watermask working.  There might be a few other URLs that need to be changed.

**Comment by EJFielding** [comment]
@kylemurray2 Thanks for spotting that other place that the URLs are hard-coded. I did a search of the whole directory tree and found some more in `DataManager` and other locations. See #562

**Comment by Xin-Wang-520** [comment]
> For some reason, I can download the URLs with `wget` from a command line, but the `curl` command that is run from inside `dem.py` is connecting but not getting any data. They should be using the same `$HOME/.netrc` file.

Teacher I also have this problem, after changing the address, but still can not download, how to solve？

**Pull request merged**
