### PR TITLE
Fix for dloadOrbits.py to reflect new download URL and minor fix in fetchOrbit.py

### PR DESCRIPTION
**Pull request by bjmarfito**
- Updated dloadOrbits.py to reflect new downloading site based on https://github.com/isce-framework/isce2/pull/801
- Removed oType variable in fetchOrbit.py since it is unused
- Fixes a bug due to a change in format in fetchOrbit.py and dloadOrbits.py  from .000Z to .000000Z in line 173 

Screenshot 2024-08-18 at 8 06 14 PM

*View of the dowloaded precise orbit files for Sentinel-1A and 1B. I tested January 1, 2020 up to January 3, 2020. Based on the screenshot it works.

For your review @rtburns-jpl @hfattahi

### CODE REVIEW

**Comment by bjmarfito** [comment]
Added a bugfix for dloadOrbits.py and fetchOrbit.py due to format change from .000Z to .000000Z.

**Comment by bjmarfito** [comment]
Hi @rtburns-jpl, can this be tested and merged?

**Review by rtburns-jpl — APPROVED** [review]
Changes look good to me, going to go ahead and merge to keep things in sync since the existing download code is broken anyway, we can address any issues in followup PRs

**Comment by bjmarfito** [comment]
Thank you!

**Pull request merged**
