### PR TITLE
Updating README to markdown

### PR DESCRIPTION
**Pull request by piyushrpt**
Updating README file to github friendly Markdown format
* Updating insarApp references to stripmapApp
* Removed outdated installation instructions 

The new file would render as shown below:
https://github.com/piyushrpt/isce2/tree/readme

### CODE REVIEW

**Comment by eric-gurrola** [comment]
Hi Piyush,

The text refers to section numbers in a few places.  Unfortunately, the markdown version didn’t keep the section numbers.  Otherwise, it looks good.

Eric

**Comment by piyushrpt** [comment]
I just updated all the numbered section references with corresponding links.

**Comment by eric-gurrola** [comment]
That works…  even better than the section numbers…

Thanks

**Review by eric-gurrola — APPROVED** [review]
Looks good.

**Pull request merged**
