### PR TITLE
Bug fixing

### PR DESCRIPTION
**Pull request by vbrancat**
Fixed some bugs in Factories.py (StripmapApp.py), RubberSheeting and runInterferogram.py

### CODE REVIEW

**Comment by piyushrpt** [comment]
Hi Virginia,
    The 2 new files need to be added to the SConscript file here: 
https://github.com/vbrancat/isce2/blob/532cfa085b49a7c22a4723f3aebe38eb2db3fd18/components/isceobj/StripmapProc/SConscript#L52

That should take care of the build error. 

Piyush

**Comment by vbrancat** [comment]
Hi  Piyush,

I added the two functions (runRubbersheetRange.py and
runRubbersheetAzimuth.py) in SConscript and pushed on github.
Should I make a new pull request?

Best,
Virginia

Il giorno mer 13 nov 2019 alle ore 18:36 piyushrpt <notifications@github.com>
ha scritto:

**Comment by piyushrpt** [comment]
The tests are failing due to astropy dependency. You can add "astropy" to this requirements line and the tests should pass:
https://github.com/isce-framework/isce2/blob/ed8f32e8b810e665d0a7a4f809193f1ef78dde66/.circleci/config.yml#L26

**Comment by piyushrpt** [comment]
Thank you. This looks good.

**Pull request merged**
